'''Состояния для обработчиков диалогов'''
class UserStates:
    TYPING_FIRST_NAME, TYPING_LAST_NAME, TYPING_DAYS, TYPING_RESULT_TYPE, TYPING_RESULT_TEXT, TYPING_RESULT_URL = range(6)


class AdminStates:
    TYPING_PASSWORD, TYPING_NEW_PASSWORD, WORKOUT_TYPING_TYPE, WORKOUT_TYPING_NAME, WORKOUT_TYPING_TEXT, TYPING_CALENDAR, TYPING_FAQ, TYPING_MAILING_TEXT = range(8)
